name: Build and deploy to GH pages
on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex

      - name: Marp Build
        uses: docker://marpteam/marp-cli:latest
        with:
          args: slides.md --html --allow-local-files
        env:
          MARP_USER: root:root

      - name: Prepare files
        run: |
          mkdir -p public
          mv paper.pdf public/
          mv slides.html public/
          mv slides.pdf public/
          echo "<html><body><h1>Project Files</h1><ul><li><a href='paper.pdf'>Paper (PDF)</a></li><li><a href='slides.html'>Slides (HTML)</a></li><li><a href='slides.pdf'>Slides (PDF)</a></li></ul></body></html>" > public/index.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public